In [5]:
from sklearn.metrics import confusion_matrix, make_scorer
# Define a function to calculate specificity
def specificity(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    specificity = tn / (tn+fp)
    return specificity

# Make a scorer from the custom specificity function
specificity_scorer = make_scorer(specificity, greater_is_better=True)

In [3]:
# Import libraries
from Cleanning import general_info, internal_payments, credit_reports
from Featurizing import get_features
from Inference import get_prediction

c:\Users\AldoErnestoEscobedoT\OneDrive - Freedom to Scale SA de CV\Documentos\challenge\classification_model\Inference.py:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype('category')
c:\Users\AldoErnestoEscobedoT\anaconda3\lib\site-packages\sklearn\utils\validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\AldoErnestoEscobedoT\anaconda3\lib\site-packages\sklearn\utils\validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():

In [10]:
# Get current features
current_features = get_features(general_info_df=general_info, internal_payments=internal_payments, credit_reports=credit_reports).sort_values(by=["user_id","limit_date"], ascending=True).drop_duplicates("user_id", keep="last")
current_features.head(20)

,application_id,application_date,documentation_date,user_id,documentation_date_new,target,limit_date,num_prev_contracts,avg_notional,pct_late_payments,...,credit_type_Otros (Múltiples Créditos),credit_type_Préstamo de Nomina,credit_type_Préstamo Empresarial,credit_type_Préstamo Garantizado,credit_type_Préstamo Personal,credit_type_Préstamo Quirografiario,credit_type_Préstamo no garantizado,credit_type_Préstamo para estudiante,credit_type_Tarjeta Departamental,credit_type_Tarjeta de Crédito
699,1,2018-04-23 00:00:00,2018-04-30 16:25:18,1000.0,2019-08-16 09:07:00,0.0,2019-08-15 00:00:00,141,56638.297872,0.312057,...,True,False,False,False,True,False,False,False,False,True
869,2,2018-07-31 15:33:05,2018-08-22 16:25:25,1001.0,2019-08-14 15:52:22,1.0,2019-08-08 00:00:00,0,50000.000000,0.250000,...,True,False,False,False,True,False,False,False,False,True
163,3,2018-08-03 11:00:10,2018-08-13 12:53:33,1002.0,2019-07-10 15:38:10,0.0,2019-07-09 00:00:00,0,50000.000000,0.166667,...,True,True,False,False,True,False,False,False,False,True
121,4,2018-09-12 18:51:52,2018-09-19 12:11:39,1003.0,2019-11-13 16:52:25,0.0,2019-11-07 00:00:00,0,50000.000000,0.066667,...,True,True,False,False,True,False,False,False,False,True
697,5,2018-09-17 14:11:45,2018-09-26 16:21:22,1004.0,2019-09-04 18:34:40,0.0,2019-09-04 00:00:00,15,100000.000000,0.333333,...,False,False,False,False,True,False,False,False,False,True
918,6,2018-09-18 00:00:00,2018-09-19 15:35:59,1005.0,2020-02-21 09:59:56,1.0,2020-02-19 00:00:00,27,506800.000000,0.080000,...,False,False,False,False,True,False,False,False,False,True
481,7,2018-09-19 16:51:21,2018-10-02 18:46:08,1006.0,2019-07-31 10:38:00,0.0,2019-07-19 00:00:00,0,30000.000000,0.045455,...,False,True,False,False,True,False,False,False,False,True
248,1073,2021-02-22 17:05:06,2021-02-23 20:19:06,1007.0,2021-08-09 15:38:26,0.0,2021-08-08 04:57:50,63,315075.873563,0.011494,...,True,False,False,False,True,False,False,False,False,True
858,295,2019-07-09 00:00:00,2019-07-19 11:35:57,1008.0,2019-12-02 11:13:02,1.0,2019-11-23 00:00:00,10,89090.909091,0.318182,...,True,False,False,False,True,False,False,False,False,True
899,338,2019-08-08 00:00:00,2019-08-09 13:41:03,1009.0,2020-02-20 17:16:46,1.0,2020-02-17 00:00:00,10,202000.000000,0.080000,...,False,False,False,False,False,False,False,False,False,True
703,11,2018-10-05 12:49:10,2018-10-08 15:01:22,1010.0,2019-08-19 17:02:25,0.0,2019-08-15 00:00:00,0,46400.000000,0.166667,...,False,True,False,False,True,False,False,False,False,True
889,287,2019-07-03 00:00:00,2019-07-04 18:27:13,1011.0,2020-02-06 13:35:41,1.0,2020-02-05 00:00:00,9,58571.428571,0.095238,...,False,False,False,False,True,False,False,False,False,True
819,13,2018-10-14 18:06:51,2018-10-23 15:11:36,1012.0,2019-07-12 17:08:03,1.0,2019-07-12 00:00:00,12,112900.000000,0.000000,...,False,False,False,False,True,False,False,False,False,True
189,621,2020-02-19 00:00:00,2020-02-19 13:29:58,1013.0,2021-01-19 20:58:59,0.0,2021-01-19 13:57:57,34,695588.235294,0.029412,...,True,False,False,False,True,False,False,False,False,True
312,1679,2021-12-19 04:40:53,2021-12-23 11:22:22,1014.0,2022-11-17 15:53:50,0.0,2022-11-10 12:55:18,38,260388.387097,0.000000,...,False,False,False,False,True,False,False,False,False,True
668,16,2018-11-07 17:32:03,2018-11-28 21:13:54,1015.0,2019-10-03 17:14:22,0.0,2019-10-02 00:00:00,0,50000.000000,0.458333,...,True,False,False,False,True,False,False,False,False,True
739,17,2018-11-12 09:26:55,2018-12-04 13:30:00,1016.0,2019-07-26 11:50:57,1.0,2019-07-24 00:00:00,0,50000.000000,0.250000,...,True,False,False,False,True,False,False,False,False,True
468,1220,2021-04-26 11:08:06,2021-04-29 16:16:59,1017.0,2022-02-11 13:51:57,0.0,2022-02-08 10:03:08,92,399941.521739,0.043478,...,False,False,False,False,True,False,False,False,False,True
330,19,2018-11-20 08:40:06,2018-11-29 09:48:02,1018.0,2019-10-16 11:06:34,0.0,2019-10-16 00:00:00,12,52400.000000,0.416667,...,False,False,False,False,False,False,False,False,False,False
657,20,2018-11-21 11:57:27,2018-11-23 19:44:17,1019.0,2019-07-17 10:17:41,0.0,2019-07-15 00:00:00,0,50000.000000,0.083333,...,False,False,False,False,True,False,False,False,False,True

In [13]:
# Calculate Scores
current_features["score"]=get_prediction(features_df=current_features)

c:\Users\AldoErnestoEscobedoT\OneDrive - Freedom to Scale SA de CV\Documentos\challenge\classification_model\Inference.py:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
c:\Users\AldoErnestoEscobedoT\anaconda3\lib\site-packages\sklearn\utils\validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\AldoErnestoEscobedoT\anaconda3\lib\site-packages\sklearn\utils\validation.py:623: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():

In [22]:
# Select top 20 clients to offer better loans
current_features.sort_values("score", ascending=False)[["user_id", "score"]].head(20)

     user_id     score
102   1023.0  0.956492
593   1145.0  0.947264
694   1857.0  0.946858
500   1242.0  0.942399
98    1248.0  0.931740
699   1000.0  0.926190
86    1184.0  0.906029
96    1120.0  0.902632
328   1178.0  0.901023
468   1017.0  0.883459
540   1087.0  0.876917
625   1683.0  0.867271
154   1037.0  0.863102
570   1440.0  0.855275
649   1851.0  0.843440
631   1657.0  0.842126
545   1231.0  0.842095
180   1318.0  0.834156
23    1123.0  0.833932
393   1032.0  0.832180